name: Run pytests

on:
  pull_request:
    branches:
      - '**'  # Tests run on all pull request branches
  push:
    branches:
      - main  # Tests run on pushes to the main branch (e.g., merges)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Run tests with coverage
      - name: Run tests
        run: pytest --cov-branch --cov-report=xml --cov=backend backend/app/tests/

      # Step 4: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: thesisgenius/thesis-genius
