name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'JIRA-*'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: thesisgenius/thesis-genius/.github/workflows/python.yml@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Linting
        run: make lint
