name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'JIRA-*'

jobs:
  setup-python:
    uses: ./.github/workflows/python.yml
    strategy:
      matrix:
        python-version: [ 3.12 ]
    with:
      python-version: ${{ matrix.python-version }} # Pass matrix version
  lint:
    needs: setup-python
    runs-on: ubuntu-latest
    steps:
      - name: Run Linting
        run: make lint
