name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'JIRA-*'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Python
        uses: ./.github/workflows/python.yml
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Linting
        run: make lint
